import { Montserrat } from "next/font/google";
import "./globals.css";
import Providers from "./(providers)/providers";
import LeftSideNav from "@/components/Layout/LeftSideNav/LeftSideNav";
import RightSideNav from "@/components/Layout/RightSideNav/RightSideNav";
import Auth from "@/AuthProvider/Auth";
import MobileNav from "@/components/MobileNav/MobileNav";
import Script from "next/script";
import NavbarMobile from "@/components/NavbarMobile/NavbarMobile";
import Users from "@/utils/users";
import Post from "@/utils/post";
import MainLayout from "@/components/Main/MainLayout";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const users = await Users();
  const posts = await Post();

  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          <Auth>
            <MainLayout users={users} posts={posts} children={children}></MainLayout>
          </Auth>
        </Providers>
      </body>
      <Script src="https://kit.fontawesome.com/47bea8806e.js" />
    </html>
  );
}
